apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: project-consumer
        imagePullPolicy: Never
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"