FROM apache/kafka:3.7.0

ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093

ENV KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

ENV KAFKA_LOG_DIRS=/tmp/kraft-combined-logs